feat: 세미나 상세 페이지 레이아웃
Sem-in-a/Semi-na-android pull request #21
Opened 2023-11-15 07:57 UTC by 2wndrhs

## ISSUE_NUM: #3 

### Description
PR에 대한 설명을 적어주세요

### ScreenShot
변경한 부분에 대한 스크린샷을 첨부해주세요

2023-11-16 23:47 UTC, JjungminLee requested changes
혹시 pr에 스크린샷 첨부 가능할까요?! 그리고 파베 연결은 아직 안한거 같은데 맞져?

2023-11-17 09:29 UTC, 2wndrhs commented
> 혹시 pr에 스크린샷 첨부 가능할까요?! 그리고 파베 연결은 아직 안한거 같은데 맞져?

스크린샷 첨부를 까먹었네요 바로 첨부하겠습니당
파이어베이스 연결은 레이아웃 먼저 만들고 나중에 구현하려구용

2023-11-17 10:44 UTC, JjungminLee commented
> > 혹시 pr에 스크린샷 첨부 가능할까요?! 그리고 파베 연결은 아직 안한거 같은데 맞져?
> 
> 스크린샷 첨부를 까먹었네요 바로 첨부하겠습니당 파이어베이스 연결은 레이아웃 먼저 만들고 나중에 구현하려구용

옹 너무 레이아웃 짱짱입니다. 파베 구조도 좀 설명 해드려야하는것 같긴해서 나중에 하셔도 될것 같아영 그러면 cloud function은 제가 할게용!

2023-11-17 10:44 UTC, JjungminLee approved these changes

2023-11-18 06:06 UTC, candosh approved these changes
ㅠㅠㅠㅠ넘 수고하셨어요 짱쭌!

2023-11-18 09:43 UTC, merged